# action.yml
name: 'Slack Notification'
author: Prakritish Sen Eshore
description: 'Send Slack Notification to given Channel'
inputs:
  slack_token:
    description: "Slack Bot Token"
    required: true
  channel:
    description: "Slack Channel ID"
    required: true
  username:
    description: "User Name to Display on the Slack Message"
    required: false
  message:
    description: 'Message'
    required: true
  result:
    description: "PASS / FAIL"
    required: false
  fields:
    description: "Text Fields"
    required: true
  
runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'inbox'
  color: 'green'
