name: Merge to main

on:
    push:
        branches: ['main']

jobs:
    build:
        name: Build
        runs-on: ['ubuntu-latest']
        steps:
            - uses: actions/checkout@v4
            - name: Install Packages
              run: yarn
            - name: Build
              run: yarn build

    test:
        name: Test
        runs-on: ['ubuntu-latest']
        needs: ['build']
        if: always()
        steps:
            - uses: actions/checkout@v4
            - name: Send Slack Message
              uses: prakritish/slack-notification@main
              with:
                slack_token: ${{ secrets.SLACK_TOKEN }}
                channel: 'D04CSFAT3R8'
                result: ${{ needs.build.result }}
                message: "The build ${{ needs.build.result }}"
